(function(){
'use strict';
function N(s){return(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase()}
function hideContact(){let e=[...document.querySelectorAll('div,section,footer,p,h1,h2,h3,h4,strong,span')].find(x=>N(x.textContent).trim()==='ENTRE EM CONTATO');if(!e)return;let p=e;for(let i=0;i<5&&p.parentElement;i++){let t=N(p.textContent);if(t.includes('WHATSAPP')&&t.includes('E-MAIL'))break;p=p.parentElement}p.style.setProperty('display','none','important')}
function homeTendencia(){const old=document.getElementById('homePremiumCardTendencia');if(old)old.style.setProperty('display','none','important');const cards=[...document.querySelectorAll('.home-feature-card')];if(!cards.length)return;let exists=document.querySelector('.home-feature-card.thor-tendencia-real');if(exists)return;const base=cards[0],grid=base.parentElement;if(!grid)return;const c=base.cloneNode(true);c.classList.add('thor-tendencia-real');c.removeAttribute('id');c.setAttribute('data-home-target','btnTendenciaAtalho');c.removeAttribute('onclick');const strong=c.querySelector('strong'),small=c.querySelector('small'),ico=c.querySelector('.hfc-icon');if(strong)strong.textContent='Tendência';if(small)small.textContent='Dezenas em alta e queda';if(ico)ico.textContent='↗';c.style.setProperty('--fc','#6d7fa8');grid.appendChild(c)}
function moveFechamento(){const tend=document.querySelector('.home-feature-card.thor-tendencia-real');if(!tend)return;const grid=tend.parentElement;if(!grid)return;let card=document.querySelector('.thor-fechamento-abaixo-tendencia');if(!card){const candidatos=[...document.querySelectorAll('div,section,button,a')].filter(e=>{const t=N(e.innerText||e.textContent);return t.includes('FECHAMENTO PERSONALIZADO')&&t.includes('MONTE SUAS DEZENAS')&&t.includes('GERAR')&&!t.includes('ULTIMO SORTEIO')});if(!candidatos.length)return;candidatos.sort((a,b)=>a.querySelectorAll('*').length-b.querySelectorAll('*').length);card=candidatos[0]}if(!card||card===grid||card.contains(grid))return;if(card.parentElement!==grid)grid.appendChild(card);card.classList.add('thor-fechamento-abaixo-tendencia');card.style.setProperty('width','auto','important');card.style.setProperty('min-width','0','important');card.style.setProperty('height','1.7cm','important');card.style.setProperty('min-height','1.7cm','important');card.style.setProperty('max-height','1.7cm','important');card.style.setProperty('margin','0','important');card.style.setProperty('box-sizing','border-box','important');card.style.setProperty('align-self','stretch','important');let gerar=[...card.querySelectorAll('button,a')].find(b=>N(b.textContent).trim()==='GERAR');if(gerar)gerar.style.setProperty('display','none','important');if(!card.dataset.thorFechamentoClick){card.dataset.thorFechamentoClick='1';card.style.setProperty('cursor','pointer','important');card.addEventListener('click',function(e){if(gerar&&e.target!==gerar){e.preventDefault();e.stopPropagation();gerar.click()}},true)}}
const API={'lotofacil':'lotofacil','mega-sena':'megasena','quina':'quina','dia-de-sorte':'diadesorte','lotomania':'lotomania','super-sete':'supersete','timemania':'timemania','mais-milionaria':'maismilionaria','dupla-sena':'duplasena'};
const LABEL={pares:'PARES',impares:'IMPARES',primos:'PRIMOS',fibonacci:'FIBONACCI',moldura:'MOLDURA',centro:'CENTRO',mult3:'MULT. DE 3',soma:'SOMA'};
function prime(n){if(n<2)return false;for(let i=2;i*i<=n;i++)if(n%i===0)return false;return true}function fib(max){let s=new Set(),a=1,b=1;while(a<=max){s.add(a);[a,b]=[b,a+b]}return s}function dims(s){return s==='lotofacil'?[5,5]:s==='mega-sena'?[6,10]:s==='quina'?[8,10]:s==='lotomania'?[10,10]:s==='dia-de-sorte'?[7,5]:null}
function stats(a,s){let f=fib(Math.max(...a)),d=dims(s),m=0,c=0;if(d){let[col,row]=d;a.forEach(n=>{let z=n-1,r=Math.floor(z/col),x=z%col;if(r===0||x===0||r===row-1||x===col-1)m++;else c++})}return{pares:a.filter(n=>n%2===0).length,impares:a.filter(n=>n%2).length,primos:a.filter(prime).length,fibonacci:a.filter(n=>f.has(n)).length,moldura:d?m:null,centro:d?c:null,mult3:a.filter(n=>n%3===0).length,soma:a.reduce((x,y)=>x+y,0)}}
function top3(a){let c={};a.filter(v=>v!=null).forEach(v=>c[v]=(c[v]||0)+1);return Object.keys(c).map(Number).sort((x,y)=>c[y]-c[x]||x-y).slice(0,3)}
async function draw(api,n){let r=await fetch('https://servicebus2.caixa.gov.br/portaldeloterias/api/'+api+(n?'/'+n:''),{cache:'no-store'});if(!r.ok)throw Error();let j=await r.json(),a=j.listaDezenas||j.dezenasSorteadasOrdemSorteio||[];return{n:+j.numero||n,nums:a.map(x=>parseInt(x,10)).filter(Number.isFinite)}}
function buttons(root){let o={};root.querySelectorAll('button').forEach(b=>{let q=N(b.textContent).trim();Object.keys(LABEL).forEach(k=>{if(q===LABEL[k]||(k==='mult3'&&q==='MULT DE 3'))o[k]=b});if(q==='FIXAS'||q.startsWith('FIXAS ('))o.fixas=b});return o}
function panels(root,needle){return[...root.querySelectorAll('div,section,fieldset')].filter(x=>N(x.innerText||x.textContent).includes(needle)).sort((a,b)=>a.querySelectorAll('*').length-b.querySelectorAll('*').length)}
function numericTargets(p){let a=[...p.querySelectorAll('button,[role="button"]')].filter(e=>/^\s*\d{1,3}\s*$/.test(e.textContent||''));if(a.length)return a;return[...p.querySelectorAll('div,span')].filter(e=>/^\s*\d{1,3}\s*$/.test(e.textContent||'')&&!e.children.length)}
function paint(e,on){e.classList.toggle('thor-auto-selected',on)}
function mark(root,key,vals){let ps=panels(root,'ESCOLHA AS QUANTIDADES DE '+LABEL[key]);if(!ps.length)return false;ps.slice(0,2).forEach(p=>numericTargets(p).forEach(e=>paint(e,vals.includes(parseInt(e.textContent,10)))));return true}
function markFix(root,vals){let grid=document.getElementById('gfcFixasGridInline');if(!grid)return false;let s=new Set(vals);[...grid.querySelectorAll('.conf-ball')].forEach(e=>paint(e,s.has(parseInt(e.dataset.n||e.textContent,10))));return true}
function fixOk(){let ok=document.getElementById('gfcFixasOkInline');if(!ok||ok.dataset.thorOkFix)return;ok.dataset.thorOkFix='1';ok.addEventListener('click',e=>{e.stopPropagation();let p=document.getElementById('gfcFixasInline');if(p)p.classList.remove('show')},true)}
function refresh(root){fixOk();let bs=buttons(root);Object.keys(LABEL).forEach(k=>{if(bs[k]&&bs[k].dataset.thorVals)mark(root,k,bs[k].dataset.thorVals.split(',').map(Number))});if(bs.fixas&&bs.fixas.dataset.thorFixas)markFix(root,bs.fixas.dataset.thorFixas.split(',').map(Number))}
function bind(root,b,key){if(!b||b.dataset.thorAutoBound)return;b.dataset.thorAutoBound='1';b.addEventListener('click',()=>{let v=(b.dataset.thorVals||'').split(',').map(Number).filter(Number.isFinite);[20,80,180,350].forEach(ms=>setTimeout(()=>mark(root,key,v),ms))})}
function bindFix(root,b){if(!b||b.dataset.thorFixBound)return;b.dataset.thorFixBound='1';b.addEventListener('click',()=>{let v=(b.dataset.thorFixas||'').split(',').map(Number).filter(Number.isFinite);[20,80,180,350].forEach(ms=>setTimeout(()=>{if(v.length)markFix(root,v)},ms))})}
async function run(root){let input=root.querySelector('.thor-auto-qtd'),go=root.querySelector('.thor-auto-run'),status=root.querySelector('.thor-auto-status');if(!input||!go)return;let qtd=Math.max(1,Math.min(100,parseInt(input.value,10)||10)),slug=root.dataset.thorLottery||'lotofacil',api=API[slug];go.disabled=true;go.textContent='...';status.textContent='';try{let first=await draw(api),draws=[first.nums];for(let i=1;i<qtd;i++){let d=await draw(api,first.n-i);if(d.nums.length)draws.push(d.nums)}let rows=draws.map(a=>stats(a,slug)),freq={},bs=buttons(root);draws.forEach(a=>a.forEach(n=>freq[n]=(freq[n]||0)+1));Object.keys(LABEL).forEach(k=>{let v=top3(rows.map(r=>r[k]));if(bs[k]&&v.length){bs[k].dataset.thorVals=v.join(',');bs[k].classList.add('thor-auto-ready');bind(root,bs[k],k)}});let fx=Object.keys(freq).map(Number).sort((a,b)=>freq[b]-freq[a]||a-b).slice(0,3);if(bs.fixas){bs.fixas.dataset.thorFixas=fx.join(',');bs.fixas.classList.add('thor-auto-ready');bindFix(root,bs.fixas)}refresh(root);status.textContent='✓';status.className='thor-auto-status ok'}catch(e){status.textContent='!';status.className='thor-auto-status err'}finally{go.disabled=false;go.textContent='CALCULAR'}}
function mount(root){if(root.querySelector('.thor-auto-calc')){refresh(root);return}let h=[...root.querySelectorAll('h1,h2,h3,div,strong')].filter(x=>N(x.textContent).trim()==='CONFIGURACOES AVANCADAS').sort((a,b)=>a.querySelectorAll('*').length-b.querySelectorAll('*').length)[0];if(!h)return;let box=document.createElement('span');box.className='thor-auto-calc';box.innerHTML='<input class="thor-auto-qtd" type="number" min="1" max="100" value="10"><button class="thor-auto-run" type="button">CALCULAR</button><span class="thor-auto-status"></span>';h.style.position='relative';h.appendChild(box);box.querySelector('.thor-auto-run').onclick=e=>{e.preventDefault();e.stopPropagation();run(root)};fixOk()}
function scan(){hideContact();homeTendencia();moveFechamento();document.querySelectorAll('.thor-fechamento-luxo').forEach(mount);fixOk()}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(scan,200));else setTimeout(scan,200);document.addEventListener('click',()=>setTimeout(scan,80),true);new MutationObserver(()=>{clearTimeout(window.__thorAutoT);window.__thorAutoT=setTimeout(scan,80)}).observe(document.documentElement,{childList:true,subtree:true});
})();